/* eslint-disable */
// Auto-generated by scripts/generate-svg-components.ts

import type { SVGProps } from "react";
import RawIcon from "../../../../../assets/scale-h.svg?react";

export function ScaleHorizontalIcon(props: SVGProps<SVGSVGElement>) {
  return <RawIcon {...props} />;
}
