import { mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const outDir = join(
  root,
  "src",
  "renderer",
  "src",
  "components",
  "generated-icons",
);

interface IconSource {
  fileName: string;
  componentName: string;
}

const iconSources: IconSource[] = [
  { fileName: "scale-h.svg", componentName: "ScaleHorizontalIcon" },
  { fileName: "scale-v.svg", componentName: "ScaleVerticalIcon" },
];

function normalizeSvgStrokeColor(svg: string): string {
  return svg
    .replace(/stroke:\s*black\b/gi, "stroke:currentColor")
    .replace(/stroke:\s*#000000\b/gi, "stroke:currentColor")
    .replace(/stroke:\s*#000\b/gi, "stroke:currentColor")
    .replace(/stroke=\"black\"/gi, 'stroke="currentColor"')
    .replace(/stroke=\"#000000\"/gi, 'stroke="currentColor"')
    .replace(/stroke=\"#000\"/gi, 'stroke="currentColor"');
}

function normalizeIconAssetColors(fileName: string): void {
  const assetPath = join(root, "assets", fileName);
  const before = readFileSync(assetPath, "utf-8");
  const after = normalizeSvgStrokeColor(before);

  if (before !== after) {
    writeFileSync(assetPath, after, "utf-8");
    console.log(`✔ normalized strokes in ${assetPath}`);
  }
}

function componentFileContent({ fileName, componentName }: IconSource): string {
  const importPath = `../../../../../assets/${fileName}?react`;

  return `/* eslint-disable */\n// Auto-generated by scripts/generate-svg-components.ts\n\nimport type { SVGProps } from "react";\nimport RawIcon from "${importPath}";\n\nexport function ${componentName}(props: SVGProps<SVGSVGElement>) {\n  return <RawIcon {...props} />;\n}\n`;
}

function indexFileContent(sources: IconSource[]): string {
  const exports = sources
    .map(
      (source) =>
        `export { ${source.componentName} } from "./${source.componentName}";`,
    )
    .join("\n");

  return `/* eslint-disable */\n// Auto-generated by scripts/generate-svg-components.ts\n\n${exports}\n`;
}

function generate(): void {
  mkdirSync(outDir, { recursive: true });

  for (const source of iconSources) {
    normalizeIconAssetColors(source.fileName);

    const filePath = join(outDir, `${source.componentName}.tsx`);
    writeFileSync(filePath, componentFileContent(source), "utf-8");
    console.log(`✔ generated ${filePath}`);
  }

  const indexPath = join(outDir, "index.ts");
  writeFileSync(indexPath, indexFileContent(iconSources), "utf-8");
  console.log(`✔ generated ${indexPath}`);
}

generate();
